### ISSUE TITLE
Siedma domáca úloha

### ISSUE THREAD

**Issue by floky279** [floky279/python-032021#1]
Ahoj Bob,

chcela by som ťa pekne poprosiť o skontrolovanie siedmej domácej úlohy. Ospravedlňujem sa za meškanie v pondelok som mala technicke problemy a potom som náhle ochorela. Bohužiaľ až dnes sa mi to podarilo spraviť. 
https://github.com/floky279/python-032021/tree/master/7

Ďakujem krásne vopred!

**Comment by redguy** [comment]
V poradku, dobra prace.
