### ISSUE TITLE
Osma domáca uloha

### ISSUE THREAD

**Issue by floky279** [floky279/python-032021#4]
Ahoj Bob, 

chcela by som ťa pekne poprosit o skontrolovanie osmej domacej ulohy : https://github.com/floky279/python-032021/tree/master/8 .

Ďakujem pekne vopre! pekny týždeň :)

**Comment by redguy** [comment]
Druhy graf z prikladu na akcie u me vypada hodne divne: ta predikovana cast je mnohem, mnohem vyssi nez historicke ceny. Mas to reseni trochu obracene: zadani je "vytvorit model a predikci (z komplet dat)  a vykreslit graf posledich 50 dni a predikce", zatimco ty vytvaris model a predikci z poslednich 50 dni a kreslis graf cele historie a predikce. Ale myslim, ze je jasne, jak to opravit, takz tohle zaviram a ukol ti zapocitavam.
