### ISSUE TITLE
Jedenásta domáca úloha

### ISSUE THREAD

**Issue by floky279** [floky279/python-032021#5]
Ahoj Bob,

posielam ti poslednu domácu úlohu : https://github.com/floky279/python-032021/tree/master/11 . Poprosila by som ťa veľmi pekne o opravu. 

Chcela by sa veľmi pekne poďakovať za tvoj čas, ktorý si trávil s nami dlhšie na cvičeniach. Tvoje detailné vysvetlenia veľmi pomohli k pochopeniu látky. A samozrejme aj za tvoju ochotu, konzultácie a nespočetný čas strávený nad našimi úlohami. Je to veľmi vďačné. 

Prajem všetko dobré, pekný zvyšok týždňa :)

**Comment by redguy** [comment]
Cviceni v poradku, dobra prace!
Dekuji za milou zpravu, bylo mi potesenim. Preju hodne stesti jak v IT tak v zivote,vesely svatky   a hodne zdravi 8)
